import httpx, json
c = httpx.Client(base_url="http://127.0.0.1:8000/api/v1", timeout=30)
r = c.get("/auth/csrf-token")
j = r.json()
print("csrf keys:", list(j.keys()))
print("csrf data keys:", list((j.get('data') or {}).keys()) if isinstance(j.get('data'), dict) else j.get('data'))
r = c.post("/auth/login", json={"username": "admin", "password": "Admin@12345"})
j = r.json()
print("login keys:", list(j.keys()))
print("login data keys:", list((j.get('data') or {}).keys()))
